// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoadFactors } from "./LoadFactors";

/**
 * User-defined calculation parameters
 */
export type StressParams = { loadFactors: LoadFactors, levelRange: [number, number], };
