// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StressResult = { level: number, pier: string, combo: string, area: number, force: number, stress: number, id: string, };
